version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: stackmotive-e2e-db
    environment:
      POSTGRES_DB: stackmotive_local
      POSTGRES_USER: stackmotive
      POSTGRES_PASSWORD: stackmotive
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stackmotive -d stackmotive_local"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - e2e_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: stackmotive-e2e-redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    image: python:3.11-slim
    container_name: stackmotive-e2e-backend
    working_dir: /app
    environment:
      DATABASE_URL: postgresql+psycopg://stackmotive:stackmotive@db:5432/stackmotive_local
      REDIS_URL: redis://redis:6379
      JWT_SECRET: e2e-test-secret-key-do-not-use-in-production
      ENVIRONMENT: development
      PYTHONPATH: /app
      PYTHONUNBUFFERED: 1
      CORS_ORIGINS: http://localhost:5174
    volumes:
      - ./server:/app/server
      - ./shared:/app/shared
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      bash -c "
        apt-get update && apt-get install -y curl &&
        pip install --no-cache-dir -r /app/server/requirements.txt &&
        pip install --no-cache-dir psycopg[binary] slowapi reportlab &&
        cd /app/server &&
        alembic upgrade head &&
        cd /app &&
        uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
      "
  frontend:
    image: node:20-slim
    container_name: stackmotive-e2e-frontend
    working_dir: /app/client
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:8001
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    ports:
      - "5174:5174"
    depends_on:
      - backend
    command: >
      sh -c "
        apt-get update &&
        apt-get install -y wget ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libdbus-1-3 libdrm2 libgbm1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libx11-6 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxkbcommon0 libxrandr2 xdg-utils &&
        npm ci &&
        npx playwright install chromium &&
        npm run build &&
        npm run preview -- --host 0.0.0.0 --port 5174
      "

volumes:
  e2e_postgres_data:

networks:
  default:
    name: stackmotive-e2e-network
