// Block 70: Strategy Preset Marketplace (vFuture)
import React from 'react';
import type { StrategyPreset } from '../../types/strategyPreset';

// Mock preset data for preview only (no real upload/clone logic)
const mockPresets: StrategyPreset[] = [
  {
    id: 'preset-1',
    name: 'Aggressive Growth (Community)',
    description: 'High-growth preset with max equity/crypto exposure.',
    overlays: [],
    weights: { BTC: 0.4, ETH: 0.3, QQQ: 0.2, XAU: 0.1 },
    parameters: { risk: 'high', rebalance: 'monthly' },
    createdBy: 'community',
    createdAt: '2025-06-01T12:00:00Z',
    auditTrail: ['Submitted by user123', 'Reviewed by admin'],
    aiNotes: 'Backtested for 3 years, high volatility.',
    backtestSummary: 'CAGR: 18%, Max Drawdown: 22%'
  },
  {
    id: 'preset-2',
    name: 'Defensive Blend (AI)',
    description: 'AI-curated blend for capital preservation.',
    overlays: [],
    weights: { XAU: 0.3, TLT: 0.3, BTC: 0.2, QQQ: 0.2 },
    parameters: { risk: 'low', rebalance: 'quarterly' },
    createdBy: 'AI',
    createdAt: '2025-05-15T09:00:00Z',
    auditTrail: ['Generated by GPT-4', 'Reviewed by admin'],
    aiNotes: 'Low volatility, suitable for conservative users.',
    backtestSummary: 'CAGR: 7%, Max Drawdown: 8%'
  }
];

// Simulate user tier (replace with real auth/tier logic)
const userTier = 'Operator'; // Only show if Operator/Sovereign

const StrategyPresetMarketplace: React.FC = () => {
  if (userTier !== 'Operator' && userTier !== 'Sovereign') {
    return (
      <div className="p-6 text-center text-red-600">
        <b>Access Restricted:</b> Only Operator/Sovereign users can view the Strategy Preset Marketplace (future feature).
      </div>
    );
  }
  return (
    <section className="max-w-3xl mx-auto p-6 bg-white dark:bg-gray-900 rounded-xl shadow-lg mt-8">
      <h2 className="text-2xl font-bold mb-4">Strategy Preset Marketplace <span className="text-xs text-yellow-500">(Future)</span></h2>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {mockPresets.map(preset => (
          <div key={preset.id} className="border rounded-lg p-4 bg-gray-50 dark:bg-gray-800 shadow-sm">
            <div className="flex items-center gap-2 mb-2">
              <span className="font-semibold text-lg">{preset.name}</span>
              <span className="ml-auto text-xs px-2 py-0.5 rounded bg-gray-200 text-gray-700">{preset.createdBy}</span>
            </div>
            <div className="text-gray-700 dark:text-gray-200 mb-2">{preset.description}</div>
            <div className="text-xs text-gray-500 mb-1">Created: {new Date(preset.createdAt).toLocaleDateString()}</div>
            <div className="text-xs text-gray-500 mb-1">Audit: {preset.auditTrail.join(' | ')}</div>
            <div className="text-xs text-blue-700 dark:text-blue-300 mb-1">AI Notes: {preset.aiNotes}</div>
            <div className="text-xs text-green-700 dark:text-green-300 mb-1">Backtest: {preset.backtestSummary}</div>
            <button className="mt-2 px-3 py-1 rounded bg-gray-300 text-gray-700 text-xs font-semibold cursor-not-allowed" disabled>
              Clone (Coming Soon)
            </button>
          </div>
        ))}
      </div>
      <div className="mt-6 text-center text-yellow-600 text-xs">
        <b>Note:</b> Upload, clone, and import logic will be enabled after tier/billing integration. All presets will have full audit trail.
      </div>
    </section>
  );
};

export default StrategyPresetMarketplace; 