import os

AUTH_SECRET_KEY = os.getenv("AUTH_SECRET_KEY") or os.getenv("STACKMOTIVE_JWT_SECRET") or "CHANGE_ME"
AUTH_REFRESH_SECRET = os.getenv("AUTH_REFRESH_SECRET") or os.getenv("STACKMOTIVE_JWT_REFRESH_SECRET")
AUTH_ALGO = os.getenv("AUTH_ALGO", "HS256")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", "30"))
REFRESH_TOKEN_EXPIRE_DAYS = int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS", "14"))
