name: E2E Evidence (Playwright)

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  e2e:
    name: e2e-evidence
    runs-on: ubuntu-latest
    timeout-minutes: 60
    continue-on-error: true  # non-blocking/optional
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Start E2E stack
        run: docker compose -f docker-compose.e2e.yml up -d --build

      - name: Install Playwright browsers
        run: docker exec stackmotive-e2e-frontend npx playwright install --with-deps

      - name: Run evidence snapshot
        run: docker exec stackmotive-e2e-frontend npm run e2e:snap || true

      - name: Archive evidence folder
        run: tar -czf e2e-evidence.tar.gz docs/qa/evidence || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: e2e-evidence
          path: e2e-evidence.tar.gz
          if-no-files-found: warn
          retention-days: 30

